### ISSUE TITLE
!!! WATCH OUT !!!

### ISSUE THREAD

**Issue by YoshuaAIL** [jiaw-z/DKT-Stereo#2]
![image1](https://github.com/jiaw-z/DKT-Stereo/assets/164142958/e54a97e9-8aae-4860-a9fb-4bc102bdad62)
<img width="465" alt="image3" src="https://github.com/jiaw-z/DKT-Stereo/assets/164142958/59ea3006-a43d-4d54-86d3-e6298420b90a">
![image2](https://github.com/jiaw-z/DKT-Stereo/assets/164142958/86bc84fd-a7ca-43ac-8151-0196e8eab56b)

**Comment by lsl-air** [comment]
啥意思，图文没看懂有啥关系

**Comment by np-csu** [comment]
what do you mean?
