### ISSUE TITLE
booster dataset 1/4分辨率理解

### ISSUE THREAD

**Issue by WanyanHuang** [jiaw-z/DKT-Stereo#4]
作者您好，booster dataset论文中说到是采用1/4分辨率，请问是不是要提前将图片resize为1/4分辨率，存在quarter中吗？还是说，立体匹配时通过n_downsample参数为2将图片调整为1/4？

**Comment by jiaw-z** [comment]
这里的quarter是提前将图像resize到1/4分辨率的，raft-stereo网络中的n_downsample是控制特征提取的分辨率。

**Comment by jiaw-z** [comment]
我不太清楚resized data zoom的具体操作是什么，我猜测可能是resize视差的时候没有把值除以对应的缩放比例，因为视差值随着分辨率变为1/4也应该在数值变为1/4。你可以参考一下我用来降采样的代码。
[downsample_booster.zip](https://github.com/jiaw-z/DKT-Stereo/files/15317537/downsample_booster.zip)

**Comment by WanyanHuang** [comment]
> 我不太清楚resized data zoom的具体操作是什么，我猜测可能是resize视差的时候没有把值除以对应的缩放比例，因为视差值随着分辨率变为1/4也应该在数值变为1/4。你可以参考一下我用来降采样的代码。 [downsample_booster.zip](https://github.com/jiaw-z/DKT-Stereo/files/15317537/downsample_booster.zip)

非常感谢，确实是这个问题。根据论文，我用了train数据集中的Washer 和 OilCan，共15组数据进行evalute，epe为0.614959，D1为7.248131，相较于论文中的10.32要好，是不是也是正确情况？

**Comment by jiaw-z** [comment]
10.32的结果是在全部训练集上训练后，把test数据集上inference的结果提交到[线上Benckmark](https://cvlab-unibo.github.io/booster-web/benchmark.html)测评的，而不是在做ablation的验证集上的结果。
